web/router.ex
defmodule VimSessions.Router do
  use VimSessions.Web, :router
  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VimSessions do
    pipe_through :browser

    get "/", IndexController, :index
    get "/about", IndexController, :about

    get "/forbidden", ErrorController, :forbidden

    get "/login",    UserController, :login
    get "/register", UserController, :show_register
    resources "/posts", PostController, only: [:index, :show]

    scope "/admin" do
      resources "/posts", AdminPostController, only: [:edit, :new, :create, :index]
    end
  end

  scope "/" do
    pipe_through :browser

    addict :routes,
      register: [controller: VimSessions.UserController, action: :register],
      logout: [controller: VimSessions.UserController, action: :logout],
      recover_password: [controller: IndexController, action: :index],
      reset_password: [controller: IndexController, action: :index]
  end
end

web/views/layout_view.ex
defmodule VimSessions.LayoutView do
  use VimSessions.Web, :view
end

web/templates/layout/app.html.eex
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>vimsessions</title>
  <meta name="description" content="vimsessions">
  <meta name="author" content="Christian Di Lorenzo">

  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
  <%= if current_user(@conn) do %>
    <div class="banner">
      Admin Access:
      <%= link "posts", to: admin_post_path(@conn, :index) %>,
      <%= link "logout", to: logout_path(@conn, :logout), method: :post %>
    </div>
  <% end %>
  <%= if get_flash(@conn, :info) do %>
    <p class="banner alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>
  <%= if get_flash(@conn, :error) do %>
    <p class="banner alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>
  <header>
    <h1 class="brand"><a href="/"><span class="green">vim</span>sessions</a></h1>
    <nav>
      <a href="/donate">donate</a>
      <a href="/videos">videos</a>
      <a href="/about">about</a>
    </nav>
  </header>
  <main>
    <section class="messages">
      <p class="error" role="alert"><%= get_flash(@conn, :error) %></p>
    </section>
    <%= @inner %>
  </main>
  <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  <script>require("web/static/js/app")</script>
</body>
</html>